App\Domain\Backup\Entity\StoredVersion:
    type: entity
    table: backup_version

    id:
        id:
            type: guid
            generator:
                strategy: UUID

    embedded:
        versionNumber:
            class: App\Domain\Backup\ValueObject\Version\VersionNumber
            columnPrefix: false

    fields:
        creationDate:
            type: datetime_immutable

    oneToOne:
        file:
            targetEntity: App\Domain\Backup\Entity\StoredFile
            joinColumn:
                name: file_id
                referencedColumnName: id

        collection:
            targetEntity: App\Domain\Backup\Entity\BackupCollection
            joinColumn:
                name: collection_id
                referencedColumnName: id
