App\Domain\Authentication\Form\AuthForm:
    exclusion_policy: NONE
    properties:
        email:
            type: string

        password:
            type: string

        roles:
            type: array

        data:
            type: App\Domain\Authentication\Form\RestrictionsForm

        expires:
            type: string

        organization:
            type: string

        about:
            type: string

        id:
            type: string
