App\Domain\Authentication\Form\RestrictionsForm:
    exclusion_policy: NONE
    properties:
        tags:
            type: array

        maxAllowedFileSize:
            serialized_name: maxAllowedFileSize
            type: integer

        allowedIpAddresses:
            serialized_name: allowedIpAddresses
            type: array

        allowedUserAgents:
            serialized_name: allowedUserAgents
            type: array
