doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '12.4'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        dql:
            string_functions:
                CAST: Oro\ORM\Query\AST\Functions\Cast

        mappings:
            App\Domain\Backup\ValueObject\Collection:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/backup/valueobject/collection'
                prefix: 'App\Domain\Backup\ValueObject\Collection'
                alias: BackupCollection

            App\Domain\Backup\Entity\Authentication:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/backup/entity/authentication'
                prefix: 'App\Domain\Backup\Entity\Authentication'
                alias: BackupAuth

            App\Domain\Backup\ValueObject\Version:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/backup/valueobject/version'
                prefix: 'App\Domain\Backup\ValueObject\Version'
                alias: BackupVOVersion

            App\Domain\Authentication\Entity:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/authentication/entity'
                prefix: 'App\Domain\Authentication\Entity'
                alias: AuthEntity

            App\Domain\Backup\ValueObject:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/backup/valueobject'
                prefix: 'App\Domain\Backup\ValueObject'
                alias: BackupVO

            App\Domain\Storage\Entity:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/storage/entity'
                prefix: 'App\Domain\Storage\Entity'
                alias: StorageEntity

            App\Domain\Backup\Entity:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/orm/backup/entity'
                prefix: 'App\Domain\Backup\Entity'
                alias: BackupEntity
