nelmio_api_doc:
    documentation:
        info:
            title: File Repository
            description: Scalable Storage API, maintained by anarchist organization
            version: 1.0.0

        securityDefinitions:
            Token:
                type: apiKey
                description: 'Value: {token}. example: "test-token-full-permissions" when application is set to APP_ENV=dev or APP_ENV=test'
                name: Token
                in: header

    areas:
        path_patterns:
            - ^/(?!\{_locale\})
