nelmio_api_doc:
    documentation:
        info:
            title: File Repository
            description: Scalable Storage API, maintained by anarchist organization
            version: '%APP_VERSION%'

        securityDefinitions:
            Token:
                type: apiKey
                description: 'Value: {token}. example: "test-token-full-permissions" when application is set to APP_ENV=dev or APP_ENV=test'
                name: _token
                in: query

    areas:
        path_patterns:
            - ^/(?!\{_locale\}|_profiler|_error|_wdt)
