nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Backup Repository
            description: Specialized ninja for backup storage. Designed to have very low resource requirements.
            version: '%APP_VERSION%'

        securityDefinitions:
            Token:
                type: apiKey
                description: 'Value: {token}. example: "test-token-full-permissions" when application is set to APP_ENV=dev or APP_ENV=test'
                name: token
                in: header

        security:
            - Token: []

    areas:
        path_patterns:
            - ^/(?!\{_locale\}|_profiler|_error|_wdt)
