minimum_ui_localized:
    resource: './minimum-ui/routes.yaml'
    prefix: '/{_locale}{_S}minimum.ui'
    requirements:
        _S: "/?"
        _locale: '|en|pl'

#minimum_ui_default_language:
#    resource: './minimum-ui/routes.yaml'
#    prefix: '/minimum.ui'
