minimumui.upload_image:
    path: /minimum.ui/upload/image
    controller: 'App\Controller\MinimumUi\UploadImageController::handle'
    methods: ['GET']
    defaults:
        _secured: true

minimumui.upload_file:
    path: /minimum.ui/upload/file
    controller: 'App\Controller\MinimumUi\UploadFileController::handle'
    methods: ['GET']
    defaults:
        _secured: true

minimumui.watch_video:
    path: /minimum.ui/watch/video/{fileId}
    controller: 'App\Controller\MinimumUi\WatchVideoController::handle'
    methods: ['GET']
    defaults:
        _secured: true
