storage.list_files:
    path: /repository
    controller: 'App\Controller\Storage\FilesListingController::handleListing'
    methods: ['GET']
    defaults:
        _secured: true

storage.upload_by_url:
    path: /repository/{type}/add-by-url
    controller: 'App\Controller\Storage\UploadByUrlController::handle'
    methods: ['POST']
    defaults:
        _secured: true
        type: image

storage.upload_by_post:
    path: /repository/{type}/upload
    controller: 'App\Controller\Storage\UploadByPostController::handle'
    methods: ['POST']
    defaults:
        _secured: true
        type: image

storage.get_file:
    path: /public/download/{filename}
    controller: 'App\Controller\Storage\ViewFileController::handle'
    methods: ['GET']
    defaults:
        _secured: false

# REST
storage.rest_delete:
    path: /repository/file/{filename}
    controller: 'App\Controller\Storage\DeleteFileController::handle'
    methods: ['DELETE']
    defaults:
        _secured: true

storage.rest_get:
    path: /repository/file/{filename}
    controller: 'App\Controller\Storage\ViewFileController::handle'
    methods: ['GET']
    defaults:
        _secured: true

storage.rest_upload_by_post:
    path: /repository/file/{filename}
    controller: 'App\Controller\Storage\UploadByPostController::handle'
    methods: ['POST']
    defaults:
        _secured: true
