minimumui.upload_image:
    path: /upload/image
    controller: 'App\Controller\MinimumUi\UploadImageController::handle'
    methods: ['GET']
    defaults:
        _secured: true

minimumui.upload_file:
    path: /upload/file
    controller: 'App\Controller\MinimumUi\UploadFileController::handle'
    methods: ['GET']
    defaults:
        _secured: true

minimumui.watch_video:
    path: /watch/video/{fileId}
    controller: 'App\Controller\MinimumUi\WatchVideoController::handle'
    methods: ['GET']
    defaults:
        _secured: true
