services:
    App\Infrastructure\Common\Test\Database\StateManager:
        public: true
        autowire: true

    App\Command\Authentication\GenerateAdminAccountCommand:
        public: true
        autowire: true
        autoconfigure: true

    App\Domain\Authentication\ActionHandler\UserCreationHandler:
        public: true
        autowire: true
        arguments:
            $expirationTime: "+2 hours"

    App\Domain\Authentication\Factory\Context\SecurityContextFactory:
        public: true
        autowire: true
