App\Domain\Authentication\Entity\User:
    type: entity
    table: users

    id:
        id:
            type: guid
            unique: true
            nullable: false
            id: true
            length: 36
            generator:
                strategy: UUID

    fields:
        data:
            type: json

        active:
            type: boolean
            options:
                default: true

        creationDate:
            type: datetime_immutable
            column: creation_date

        salt:
            type: string
            column: password_salt

    embedded:
        email:
            class: App\Domain\Authentication\ValueObject\Email
            columnPrefix: false

        passphrase:
            class: App\Domain\Authentication\ValueObject\Password
            columnPrefix: false

        organization:
            class: App\Domain\Authentication\ValueObject\Organization
            columnPrefix: false

        permissions:
            class: App\Domain\Authentication\ValueObject\Permissions
            columnPrefix: false

        about:
            class: App\Domain\Authentication\ValueObject\About
            columnPrefix: false

        expirationDate:
            class: App\Domain\Authentication\ValueObject\ExpirationDate
            columnPrefix: false
