- name: "Setup test environment"
  run: "rkd :run"
  working-directory: "integration-env"

- name: "Run API tests"
  run: "rkd :install :test --docker"
  if: ${{ always() }}
  working-directory: "api-tests"

- name: "Dump logs from environment"
  if: ${{ always() }}
  run: "rkd :logs > api-tests.log"
  working-directory: "integration-env"

- name: "Rebuild test environment"
  run: "rkd :run"
  if: ${{ always() }}
  working-directory: "integration-env"

- name: "Run E2E tests"
  if: ${{ always() }}
  run: "rkd :install :test --docker --tags='~@docker'"
  working-directory: "e2e"

- name: "Dump logs from environment"
  if: ${{ always() }}
  run: "rkd :logs > e2e.log"
  working-directory: "integration-env"

- name: "Store logs from tests execution"
  uses: actions/upload-artifact@v2
  if: ${{ always() }}
  with:
      name: tests-logs
      path: |
        integration-env/*.log
        integration-env/data/screenshots/*.png
