version: "3.5"

#
# This file extends docker-compose.yaml by adding additional services and environment variables to existing services
#

services:
    mariadb:
        ports:
            - "3306:3306"
