version: "3.5"

#
# This file extends docker-compose.yaml by adding additional services and environment variables to existing services
#

services:
    postgresql:
        ports:
            - "5432:5432"
