version: "3.5"

#
# This file extends docker-compose.yaml by adding additional services and environment variables to existing services
#

volumes:
    postgres_data:
    filerepository_data:

services:
    filerepository:
        volumes:
            - "../:/var/www/html"
            - "./tests_output:/var/www/html/tests/Functional/_output"
        environment:
            APP_ENV: "dev"
        ports:
            - "8000:80"

    #
    # Serves static files used in tests
    #
    test-webserver:
        image: nginx:1
        expose:
            - "80"
        volumes:
            - "../../examples:/usr/share/nginx/html"
