version: "3.5"

#
# This file extends docker-compose.yaml by adding additional services and environment variables to existing services
#

volumes:
    mysqld_socket:

services:
    filerepository:
        volumes:
            - mysqld_socket:/var/run/mysqld/
        environment:
            DATABASE_DRIVER: "pdo_mysql"
            DATABASE_VERSION: "5.8"
            DATABASE_URL: "pdo-mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@localhost/${MYSQL_DB}?unix_socket=/var/run/mysqld/mysqld.sock"

            DATABASE_HOST: "/var/run/mysqld/mysqld.sock"
            DATABASE_NAME: "${MYSQL_DB}"
            DATABASE_PASSWORD: "${MYSQL_PASSWORD}"
            DATABASE_USER: "${MYSQL_USER}"
            DATABASE_PORT: "3306"

    mariadb:
        image: mariadb:10.4
        volumes:
            - mysqld_socket:/var/run/mysqld/
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DB}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"