version: "3.4"

services:
    db:
        image: postgres:12.4
        environment:
            POSTGRES_USER: chomsky
            POSTGRES_PASSWORD: chomsky
            POSTGRES_DATABASE: chomsky
        volumes:
            - ./postgres/entrypoint.d:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432

    storage:
        image: minio/minio:latest
        command: server /data
        environment:
            MINIO_ACCESS_KEY: "RIOTKIT161ACABEXAMPL"
            MINIO_SECRET_KEY: "wJalrFUckFEMI/THEdENG/STaTeandCAPITALKEY"
        ports:
            - 9000:9000

    db_admin:
        image: adminer:4.7.7-standalone
        links:
            - db
        ports:
            - 8081:8080
        environment:
            ADMINER_DEFAULT_SERVER: "db"
            ADMINER_PLUGINS: "tables-filter json-column table-structure table-indexes-structure"
