authentication.create_user:
    path: /api/stable/auth/user
    controller: 'App\Controller\Authentication\CreateUserController::generateAction'
    methods: ['POST']
    defaults:
        _secured: true

# @todo: Edit user...

authentication.search:
    path: /api/stable/auth/user/search
    controller: '\App\Controller\Authentication\UserSearchController::searchAction'
    methods: ['GET']
    defaults:
        _secured: true

authentication.lookup:
    path: /api/stable/auth/user/by-id/{userId}
    controller: 'App\Controller\Authentication\LookupUserController::handle'
    methods: ['GET']
    defaults:
        _secured: true

authentication.delete:
    path: /api/stable/auth/user/by-id/{userId}
    controller: 'App\Controller\Authentication\RevokeUserAccountController::handle'
    methods: ['DELETE']
    defaults:
        _secured: true

authentication.roles_listing:
    path: /api/stable/auth/roles
    controller: 'App\Controller\Authentication\RolesListingController::handle'
    methods: ['GET']
    defaults:
        _secured: true

authentication.generate_api_token:
    path: /api/stable/auth/token/generate
    controller: 'App\Controller\Authentication\AccessTokenGenerationController::generateAction'
    methods: ['POST']
    defaults:
        _secured: true

# @todo: Revoke token - user can revoke it's token, admin can revoke anyone token
