authentication.generate_token:
    path: /auth/token/generate
    controller: 'App\Controller\Authentication\GenerateTokenController::generateAction'
    methods: ['POST']
    defaults:
        _secured: true


authentication.clear_expired_tokens:
    path: /jobs/token/expired/clear
    controller: 'App\Controller\Authentication\ClearExpiredTokensController::clearAction'
    methods: ['GET']
    defaults:
        _secured: true


authentication.roles_listing:
    path: /auth/roles
    controller: 'App\Controller\Authentication\RolesListingController::handle'
    methods: ['GET']
    defaults:
        _secured: true


authentication.lookup:
    path: /auth/token/{token}
    controller: 'App\Controller\Authentication\LookupTokenController::handle'
    methods: ['GET']
    defaults:
        _secured: true


authentication.delete:
    path: /auth/token/{token}
    controller: 'App\Controller\Authentication\DeleteTokenController::handle'
    methods: ['DELETE']
    defaults:
        _secured: true

