authentication.create_user:
    path: /api/stable/auth/user
    controller: 'App\Controller\Authentication\CreateEditUserController::modifyAction'
    methods: ['POST']

authentication.edit_user:
    path: /api/stable/auth/user/{userId}
    controller: 'App\Controller\Authentication\CreateEditUserController::modifyAction'
    methods: ['PUT']

authentication.search:
    path: /api/stable/auth/user
    controller: '\App\Controller\Authentication\UserSearchController::searchAction'
    methods: ['GET']

authentication.lookup:
    path: /api/stable/auth/user/{userId}
    controller: 'App\Controller\Authentication\LookupUserController::handle'
    methods: ['GET']

authentication.delete:
    path: /api/stable/auth/user/{userId}
    controller: 'App\Controller\Authentication\RevokeUserAccountController::handle'
    methods: ['DELETE']

authentication.roles_listing:
    path: /api/stable/auth/roles
    controller: 'App\Controller\Authentication\RolesListingController::handle'
    methods: ['GET']

#
# JWT access tokens management
#

authentication.generate_api_token:
    path: /api/stable/auth/token
    controller: 'App\Controller\Authentication\AccessTokenGenerationController::generateAction'
    methods: ['POST']

authentication.list_api_tokens:
    path: /api/stable/auth/token
    controller: 'App\Controller\Authentication\AccessTokenListingController::listAction'
    methods: ['GET']

authentication.revoke_api_token:
    path: /api/stable/auth/token/{tokenHash}
    controller: 'App\Controller\Authentication\AccessTokenRevokingController::revokeAction'
    methods: ['DELETE']
