backup.collection_create_and_edit:
    path: /repository/collection
    controller: 'App\Controller\Backup\Collection\CreateEditController::handleAction'
    methods: ['POST', 'PUT']
    defaults:
        _secured: true


backup.collection_delete:
    path: /repository/collection/{id}
    controller: 'App\Controller\Backup\Collection\DeleteController::handleAction'
    methods: ['DELETE']
    defaults:
        _secured: true


backup.collection_fetch:
    path: /repository/collection/{id}
    controller: 'App\Controller\Backup\Collection\FetchController::handleAction'
    methods: ['GET']
    defaults:
        _secured: true


backup.collection_listing:
    path: /repository/collection
    controller: 'App\Controller\Backup\Collection\ListingController::handleAction'
    methods: ['GET']
    defaults:
        _secured: true

backup.collection_list_accesses:
    path: /repository/collection/{id}/access
    controller: 'App\Controller\Backup\Security\ListGrantedUsersForCollectionController::listTokensAction'
    methods: ['GET']
    defaults:
        _secured: true

backup.collection_add_token:
    path: /repository/collection/{id}/access
    controller: 'App\Controller\Backup\Security\GrantUserToCollectionController::handleAction'
    methods: ['POST']
    defaults:
        _secured: true


backup.collection_delete_token:
    path: /repository/collection/{id}/access/{tokenId}
    controller: 'App\Controller\Backup\Security\RevokeUserAccessForCollectionController::handleAction'
    methods: ['DELETE']
    defaults:
        _secured: true


backup.submit_version:
    path: /repository/collection/{collectionId}/{naming}
    controller: 'App\Controller\Backup\Version\SubmitVersionController::handleAction'
    methods: ['POST']
    defaults:
        _secured: true
        naming: (backup|version)

backup.list_versions:
    path: /repository/collection/{collectionId}/{naming}
    controller: 'App\Controller\Backup\Version\VersionListingController::handleAction'
    methods: ['GET']
    defaults:
        _secured: true

        naming: (backup|version)

backup.delete_version:
    path: /repository/collection/{collectionId}/{naming}/{backupId}
    controller: 'App\Controller\Backup\Version\VersionDeleteController::handleAction'
    methods: ['DELETE']
    defaults:
        _secured: true

        naming: (backup|version)

backup.fetch_version:
    path: /repository/collection/{collectionId}/{naming}/{backupId}
    controller: 'App\Controller\Backup\Version\FetchController::handleAction'
    methods: ['GET']
    defaults:
        _secured: true

        naming: (backup|version)
