replication.dump_all:
    path: /replication/list
    controller: 'App\Controller\Replication\GenerateReplicationListController::dumpAction'
    methods: ['GET']
    defaults:
        _secured: true

replication.files.submitdata.schema:
    path: /replication/submitdata/schema/{name}.json
    controller: 'App\Controller\Replication\SchemaServingController::dumpSchemaAction'
    methods: ['GET']
    defaults:
        _secured: false

replication.files.submitdata.fetch:
    path: /replication/file/{fileName}/submitdata
    controller: 'App\Controller\Replication\SubmitData\DumpFileSubmitDataController::dumpSubmitDataAction'
    methods: ['GET']
    defaults:
        _secured: true

replication.files.content.fetch:
    path: /replication/file/{fileName}/content
    controller: 'App\Controller\Replication\ServeFileController::fetchAction'
    methods: ['GET']
    defaults:
        _secured: true
