storage.list_files:
    path: /repository
    controller: 'App\Controller\Storage\FilesListingController::handleListing'
    methods: ['GET']
    defaults:
        _secured: true
        _access_in_replica_mode: local

storage.upload_by_url:
    path: /repository/{type}/add-by-url
    controller: 'App\Controller\Storage\UploadByUrlController::handle'
    methods: ['POST']
    defaults:
        _secured: true
        _access_in_replica_mode: redirect-to-primary
        type: image

storage.upload_by_post:
    path: /repository/{type}/upload
    controller: 'App\Controller\Storage\UploadByPostController::handle'
    methods: ['POST']
    defaults:
        _secured: true
        _access_in_replica_mode: redirect-to-primary
        type: image

# REST
storage.rest_delete:
    path: /repository/file/{filename}
    controller: 'App\Controller\Storage\DeleteFileController::handle'
    methods: ['DELETE']
    defaults:
        _secured: true
        _access_in_replica_mode: redirect-to-primary

storage.rest_upload_by_post:
    path: /repository/file/{filename}
    controller: 'App\Controller\Storage\UploadByPostController::handle'
    methods: ['POST']
    defaults:
        _secured: true
        _access_in_replica_mode: redirect-to-primary
