
technical.hello:
    path: /
    controller: 'App\Controller\Technical\HelloController::sayHelloAction'
    methods: ['GET']

technical.version:
    path: /api/stable/version
    controller: 'App\Controller\Technical\HelloController::showVersionAction'
    methods: ['GET']

technical.healthcheck:
    path: /health
    controller: 'App\Controller\Technical\HealthController::healthAction'
    methods: ['GET']

technical.dashboard:
    path: /api/stable/metrics
    controller: 'App\Controller\Technical\DashboardController::showMetricsAction'
    methods: ['GET']

influx_metrics:
    path: /metrics/backup_repository_report/influxdb
    controller: 'App\Controller\Technical\DashboardController::showMetricsAction'
    methods: ['GET']
    defaults:
        format: influxdb

app.swagger:
    path: /api/stable/doc.json
    controller: 'App\Controller\Technical\SwaggerDocsController::serveSwaggerFileAction'
    methods: ['GET']
