
technical.hello:
    path: /
    controller: 'App\Controller\Technical\HelloController::sayHelloAction'
    methods: ['GET']
    defaults:
        _secured: false


technical.version:
    path: /api/stable/version
    controller: 'App\Controller\Technical\HelloController::showVersionAction'
    methods: ['GET']
    defaults:
        _secured: true


technical.healthcheck:
    path: /health
    controller: 'App\Controller\Technical\HealthController::healthAction'
    methods: ['GET']
    defaults:
        _secured: false

