App\Domain\Storage\Entity\Attribute:
    type: entity
    table: file_attributes

    id:
        id:
            type: guid
            length: 36
            generator:
                strategy: UUID

    fields:
        name:
            type: string
            unique: true
            length: 64

        value:
            type: string
            unique: true
            length: 1024

        dateAdded:
            type: datetime
            column: dateAdded

    manyToOne:
        storedFile:
            targetEntity: StoredFile
            joinColumn:
                name: stored_file_id
                referencedColumnName: id

