App\Domain\Backup\Entity\UserAccess:
    type: entity
    table: collection_users

    id:
        collectionId:
            type: string

        userId:
            type: string

    embedded:
        roles:
            class: \App\Domain\Backup\ValueObject\CollectionSpecificPermissions
            columnPrefix: false

    manyToOne:
        user:
            targetEntity: \App\Domain\Backup\Entity\Authentication\User
            joinColumn:
                name: user_id
                referencedColumnName: id
