version: "3.6"

services:
    # ====================================
    # Services used in integration testing
    # ====================================

    db_mysql:
        image: "mariadb:10.4"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3306:3306"

    db_postgres:
        image: "postgres:13.1-alpine"
        environment:
            POSTGRES_PASSWORD: "communism-cannot-be-enforced"
            POSTGRES_USER: "bakunin"
            POSTGRES_DB: "riotkit"
        ports:
            - "5433:5432"
