version: "3.6"

services:
    # =================================
    # Creates a test bucket for testing
    # =================================
    s3_provision:
        image: minio/mc:RELEASE.2021-02-19T05-34-40Z
        entrypoint: >
            /bin/bash -c ' set -e;
            echo " >> Configuring host";
            /usr/bin/mc config host add --api=S3v2 test_s3 http://storage:9000 "RIOTKIT161ACABEXAMPL" "wJalrFUckXEMI/THEdEZG/STaTeandCAPITALKEY";
            echo " >> Removing existing bucket";
            /usr/bin/mc rb --force test_s3/malatesta || true;
            echo " >> Creating a new bucket";
            /usr/bin/mc mb test_s3/malatesta;
            exit 0;
            '
