App\Domain\Backup\Entity\Authentication\User:
    type: entity
    table: users
    read_only: true

    id:
        id:
            type: guid
            unique: true
            nullable: false
            id: true
            length: 36
            generator:
                strategy: UUID

    fields:
        data:
            type: json

    embedded:
        permissions:
            # @todo: Move VO also to Backup domain
            class: App\Domain\Authentication\ValueObject\Permissions
            columnPrefix: false

        email:
            class: App\Domain\Backup\ValueObject\Email
            columnPrefix: false


