App\Domain\SecureCopy\Entity\CryptoMap:
    type: entity
    table: crypto_map
    read_only: false

    id:
        hash:
            type: string
            unique: true
            nullable: false
            id: true
            length: 128
            generator:
                strategy: NONE

    fields:
        plain:
            type: string
            column: plain

        type:
            type: string
            column: type
