version: "3.5"

#
# This file extends docker-compose.yaml by adding additional services and environment variables to existing services
#

volumes:
    minio_data:

services:
    filerepository:
        environment:
            FS_ADAPTER: "awss3v3"
            FS_AWSS3V3_CLIENT: "s3_client"
            FS_AWSS3V3_BUCKET: "testbucket"
            FS_AWSS3V3_PREFIX: ""
            FS_AWSS3V3_OPTIONS_ENDPOINT: "http://s3-minio-test:9000"
            FS_AWSS3V3_VERSION: "latest"
            FS_AWSS3V3_REGION: "eu-central-1"
            FS_AWSS3V3_KEY: "${MINIO_ACCESS_KEY}"
            FS_AWSS3V3_SECRET: "${MINIO_SECRET_KEY}"

    #
    # Serves
    #
    s3-minio-test:
        image: minio/minio:RELEASE.2019-09-11T19-53-16Z
        expose:
            - "9000"
        command: server /data
        volumes:
            - minio_data:/data
        environment:
            MINIO_DOMAIN: "${MINIO_DOMAIN}"
            MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
            MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"

    #
    # Create a Min.io bucket at start
    #
    provision.s3-minio-test:
        image: minio/mc
        depends_on:
            - s3-minio-test
        entrypoint: >
            /bin/sh -c '
            sleep 5;
            /usr/bin/mc config host add test_s3 http://s3-minio-test:9000 international_workers_association six_hour_workingday_for_everybody;
            echo " >> Removing existing bucket";
            /usr/bin/mc rm -r --force test_s3/testbucket || true;
            echo " >> Creating a new bucket";
            /usr/bin/mc mb test_s3/testbucket;
            echo " >> Setting a policy on the bucket";
            /usr/bin/mc policy download test_s3/testbucket;
            exit 0;
            '
