version: "3.5"

#
# This file extends docker-compose.yaml by adding additional services and environment variables to existing services
#

volumes:
    redis_cache:

services:
    filerepository:
        environment:
            CACHE_ADAPTER_TYPE: "cache.adapter.redis"
            CACHE_REDIS_URL: "redis://cache"

    cache:
        image: redis:3-alpine
        volumes:
            - redis_cache:/data
        command: "redis-server --appendonly yes"
