version: "3.5"

#
# This file extends docker-compose.yaml by adding additional services and environment variables to existing services
#

services:
    # for testing purpose we need to run fully inside of the docker container
    # so any redirects should be generated properly for internal docker network for tests execution
    # For manual tests we would keep eg. http://localhost, on production https://api.storage.riotkit.org
    filerepository:
        container_name: "${COMPOSE_ENV_NAME}_filerepository_1" # workaround for Compose bug that causes suffixes breaking CI builds
        environment:
            BASE_URL: http://filerepository

    bahub:
        image: quay.io/riotkit/bahub:dev
        container_name: "${COMPOSE_ENV_NAME}_bahub_1" # workaround for Compose bug that causes suffixes breaking CI builds
        volumes:
            - "../bahub-client:/bahub"
            - "../bahub-client/tests/bahub-test.conf.yaml:/bahub.conf.yaml:ro"
            - "../bahub-client/tests/cron:/cron:ro"
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            TEST_MODE_USE_LOCAL_PACKAGE: "true"
            TEST_SERVER_URL: "http://filerepository"
        env_file:
            - .env

    bahub_test_www:
        image: nginx:1.17
        volumes:
            - ../examples/files/www:/var/www/html

    bahub_test_mariadb:
        image: mariadb/server:10.4
        environment:
            MARIADB_DATABASE: test_www_db
            MARIADB_USER: test_www_user
            MARIADB_ROOT_PASSWORD: root
            MARIADB_PASSWORD: password
