name: "Backup Repository release workflow"
on:
    create:
        tags:
            - v*

jobs:
    "release":
        runs-on: ubuntu-20.04
        steps:
            - name: "Checkout"
              uses: actions/checkout@v1

            - name: "Login to quay"
              uses: docker/login-action@v1
              with:
                  registry: quay.io
                  username: ${{ secrets.QUAY_USERNAME }}
                  password: ${{ secrets.QUAY_PASSWORD }}

            # —— Dependencies ——————————————————————————————————————————————————
            - name: "Install build dependencies"
              run: "sudo pip install -r ./requirements.txt"
              working-directory: "server"

            - name: Setup PHP, extensions and composer
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "7.4"
                  extensions: mbstring, ctype, iconv, intl, fileinfo, openssl, filter, iconv, json, mbstring, pdo, pdo_pgsql
                  tools: symfony, composer
              env:
                  update: true

            # —— Build —————————————————————————————————————————————————————————
            - name: "Build swagger documentation"
              run: "rkd :release:swagger-docs"
              working-directory: "server"

            - name: "Build manual documentation"
              run: "rkd :release:docs"
              working-directory: "server"

            - name: "Build and push distribution package"
              run: "rkd :release:dist-zip"
              working-directory: "server"

            - name: "Build and push docker image"
              run: "rkd :release:docker-image"
              working-directory: "server"

            # —— Archive packages ——————————————————————————————————————————————
            - name: "Archive distribution package"
              uses: actions/upload-artifact@v2
              if: ${{ always() }}
              with:
                  name: complete-distributable-package.tar.gz
                  path: server/var/dist.tar.gz

            - name: "Archive API documentation"
              uses: actions/upload-artifact@v2
              if: ${{ always() }}
              with:
                  name: api-documentation.swagger.json
                  path: server/swagger.json

            - name: "Archive manual documentation"
              uses: actions/upload-artifact@v2
              if: ${{ always() }}
              with:
                  name: manual-documentation.zip
                  path: docs/build/html

            # —— Create a new release ——————————————————————————————————————————
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                draft: true
                prerelease: false

            # —— Add release artifacts ——————————————————————————————————————————
            - name: Add distribution package to release
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: server/var/dist.tar.gz
                asset_name: backup-repository-${{ github.ref }}.tar.gz
                asset_content_type: application/tar+gzip

            - name: Add API documentation to release
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: server/swagger.json
                asset_name: backup-repository-${{ github.ref }}.swagger.json
                asset_content_type: application/json

            - name: Add manual documentation to the release
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: docs/build/html
                asset_name: backup-repository-${{ github.ref }}-manual.zip
                asset_content_type: application/zip
