name: "Backup Repository Server testing workflow"
on:
    push:
    pull_request:
        branches:
            - master
            - primary

jobs:
    "test_each_new_commit":
        runs-on: ubuntu-20.04
        steps:
            - name: "Checkout"
              uses: actions/checkout@v1

            # —— Dependencies —————————————————————————————————————————————————————————
            - name: "Install CI OS dependencies"
              run: "apt-get install libssl-dev libcurl4-openssl-dev python-dev"

            - name: "Install project dependencies"
              run: "sudo pip install -r ./requirements-dev.txt -r ./bahub/requirements.txt"

            - name: Setup PHP, extensions and composer
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "7.4"
                  extensions: mbstring, ctype, iconv, intl, fileinfo, openssl, filter, iconv, json, mbstring, pdo, pdo_pgsql
                  tools: symfony, composer
              env:
                  update: true

            # —— Tests —————————————————————————————————————————————————————————
            - name: "Server: Unit tests"
              run: "rkd :test:unit"
              if: ${{ always() }}  # @todo: Remove
              working-directory: "server"

            - name: "Bahub client: Unit tests"
              run: "rkd :test:unit"
              if: ${{ always() }}  # @todo: Remove
              working-directory: "bahub"

            # —— Reports ———————————————————————————————————————————————————————
            - name: "Make HTML report from server unit tests"
              run: "rkd :test:unit:html"
              if: ${{ always() }}
              working-directory: "server"

            - name: "Archive results"
              uses: actions/upload-artifact@v2
              if: ${{ always() }}
              with:
                  name: tests-results
                  path: server/var/tests

            - name: "Archive logs"
              uses: actions/upload-artifact@v2
              if: ${{ always() }}
              with:
                  name: logs
                  path: server/var/log

    "release_dev_dockers":
        needs: test_each_new_commit
        runs-on: ubuntu-20.04
        steps:
            - name: "Checkout"
              uses: actions/checkout@v1

            - name: "Login to quay"
              uses: docker/login-action@v1
              with:
                  registry: quay.io
                  username: ${{ secrets.QUAY_USERNAME }}
                  password: ${{ secrets.QUAY_PASSWORD }}

            - name: "Install build dependencies"
              run: "sudo pip install -r ./requirements.txt"
              working-directory: "server"

            - name: "Server: Build docker image"
              run: "rkd :build:docker"
              working-directory: "server"

            - name: "Install build dependencies"
              run: "sudo pip install -r ./requirements-dev.txt"
              working-directory: "bahub"

            - name: "Bahub client: Build docker image"
              run: "rkd :build:docker"
              working-directory: "bahub"

            - name: "Save server docker image as artifact"
              run: "docker save quay.io/riotkit/backuprepository:latest-dev > server.docker.tar.gz"

            - name: "Save bahub docker image as artifact"
              run: "docker save quay.io/riotkit/bahub:latest-dev > bahub.docker.tar.gz"

#    "test_integration_each_new_commit":
#        needs: release_dev_dockers
#        runs-on: ubuntu-20.04

#    "release_dockers":
#        needs: test_integration_each_new_commit
#        runs-on: ubuntu-20.04
#
#    "release_dist":
#        needs: test_integration_each_new_commit
#        runs-on: ubuntu-20.04
